### ISSUE TITLE
Mac M1 aarch64 support

### ISSUE THREAD

**Issue by Twansparant** [vagrant-landrush/landrush-ip#8] opened 2022-02-08 10:51 UTC
Hi there,

I'm using the full Roots stack for a Wordpress multisite project. **Trellis** uses the vagrant plugin [Landrush](https://github.com/vagrant-landrush/landrush) for managing DNS for the subdomains, which uses [landrush-ip](https://github.com/vagrant-landrush/landrush-ip/) internally.

Following up on this [Roots Discourse topic](https://discourse.roots.io/t/vagrant-up-fails-on-executing-landrush-ip-on-m1-mac/22157):

Running `vagrant up` on my new **M1** Macbook Pro results in an error:
```
Unsupported architecture
```

So I tried adding the `aarch64` architecture on [line 10](https://github.com/vagrant-landrush/landrush-ip/blob/e4de811cd0f8b2f07be18767042450e0b386132a/lib/landrush-ip/cap/linux/landrush_ip_install.rb#L10), but that results in a new error:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/usr/local/bin/landrush-ip -yaml
Stdout from the command:
Stderr from the command:
bash: line 4: /usr/local/bin/landrush-ip: cannot execute binary file: Exec format error
exit status 1
```

Is the ARM based architecture not supported at all, or am I missing something?
Thanks!

**Comment by Twansparant** [comment] 2022-02-09 08:23
I found [this issue on gox](https://github.com/mitchellh/gox/issues/92) regarding `linux/arm64`.

**Comment by E-VANCE** [comment] 2022-03-16 12:56
Also ran into this issue, so +1 for merging the corresponding PR #9 ! @Werelds 

Thanks @Twansparant for digging into this!!

**Comment by Werelds** [comment] 2022-03-16 13:06
Hi everyone,

I'll see if I can take a look at this in the next few days. I must admit that I haven't actually used Vagrant in years, so I'll need to sort out a minimal setup to check as well.

**Comment by evankford** [comment] 2022-04-27 02:02
@Werelds Any chance you could merge the PR that updates to support ARM/M1 architecture? I can confirm that it works after building/replacing in my filesystem.

**Comment by Werelds** [comment] 2022-04-27 07:38
Yes, will do, apologies. Took me a while to get a setup going again and I've had to travel in between as well, but I should be able to double-check this in the next couple of days. I might also see if I can modernise all of this altogether, because obviously a lot of this code is ancient at this point.

**Comment by Werelds** [comment] 2022-04-29 13:34
Merged the PR, built and pushed the updated Gem. Let me know if everything's alright now @evankford @Twansparant @E-VANCE and I'll close the issue.

**Comment by Twansparant** [comment] 2022-04-29 14:21
I just uninstalled & re-installed the `vagrant landrush` plugin and it's now installing the new `landrush-ip-0.2.7` gem with the fix and I can confirm it's working for me now on my multisite project on my M1.
Thanks a lot for your help!

**Comment by evankford** [comment] 2022-05-03 19:10
@Werelds Same! Can confirm, helps me out a lot! Thanks for the quick update!

**Comment by Werelds** [comment] 2022-05-04 07:24
Great, I'll close this now then!

**Closed as completed by Werelds** 2022-05-04 07:24 UTC
